In [1]:
from PIL import Image
import glob
import numpy as np
import os
from os.path import basename

image_Lbl_list = []
for filename in glob.glob('Dataset/*.png'): #assuming png
    im = Image.open(filename)
    label = (filename.split("_")[1])
    #print(label)
    image_Lbl_list.append(label)
    im.close()

#print(image_Lbl_list)

In [2]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt

flat_Image_List = [] # new list containing flatten image arrays
#for img in image_Lbl_list: # iterate over the images contained in the directory
for filename in glob.glob('Dataset/*.png'):
    im = Image.open(filename)
    img = np.reshape(im, (12288))
    flat_Image_List.append(img) # Append to the list 
    #plt.imshow(img)
    im.close()
    #print(flat_Image_List)

#print(flat_Image_List)

In [3]:
labels = 15
imageSize = 12288

In [4]:
from numpy import array

xTrain = array(flat_Image_List)

#print(flat_Image_List)
print(xTrain)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [5]:
# Converts RGB to a range between 0-1
xTrain = xTrain/255

In [30]:
xTrain = np.reshape(xTrain,(73055, 64, 64, 3))

In [36]:
input_shape = (64, 64, 3)

In [37]:
xTrain = xTrain.astype('float32')

In [38]:
# For encoding categorical variables and pre processing.
import sklearn.preprocessing as pre
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

encoder = pre.LabelBinarizer()
encoder.fit(image_Lbl_list)
outputs = encoder.transform(image_Lbl_list)

#xTrain.reshape(100, 12288)

inputs = xTrain
#inputs.reshape(len(xTrain), imageSize)
inputs.shape

(73055, 64, 64, 3)

In [39]:
# ------- MODEL -------
# Import keras.
import keras as kr
import tensorflow as tf

# Importing the required Keras modules containing model and layers
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D

# Start a neural network, building it by layers.
model = kr.models.Sequential()
# Add a hidden layer with 784 neurons.
model.add(Conv2D(64, kernel_size=(3,3), input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(10,activation=tf.nn.softmax))

# Add a 15 neuron output layer.
model.add(kr.layers.Dense(units=15, activation='softmax'))

In [40]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 62, 62, 64)        1792      
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 31, 31, 64)        0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 61504)             0         
_________________________________________________________________
dense_11 (Dense)             (None, 128)               7872640   
_________________________________________________________________
dropout_6 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_12 (Dense)             (None, 10)                1290      
_________________________________________________________________
dense_13 (Dense)             (None, 15)                165       
Total para

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# Number of Epoch is the amount of times the training set is put through the model
# The batch size is the amount of images the models processes at one time
model.fit(x=inputs,y=outputs, epochs=10, batch_size=120)

Epoch 1/10
13440/73055 [====>.........................] - ETA: 11:18 - loss: 2.6991 - acc: 0.1118