In [1]:
from PIL import Image
import glob
import numpy as np
import os
from os.path import basename

image_Lbl_list = []
for filename in glob.glob('Images/*.png'): #assuming png
    im = Image.open(filename)
    label = (filename.split("_")[1])
    #print(label)
    image_Lbl_list.append(label)
    im.close()

#print(image_Lbl_list)

In [2]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt

flat_Image_List = [] # new list containing flatten image arrays
#for img in image_Lbl_list: # iterate over the images contained in the directory
for filename in glob.glob('Images/*.png'):
    im = Image.open(filename)
    img = np.reshape(im, (12288))
    flat_Image_List.append(img) # Append to the list 
    #plt.imshow(img)
    im.close()
    #print(flat_Image_List)

#print(flat_Image_List)

In [3]:
labels = 15
imageSize = 12288

In [4]:
from numpy import array

xTrain = array(flat_Image_List)

#print(flat_Image_List)
print(xTrain)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [5]:
yTrain = array(image_Lbl_list)
print(yTrain)

['0' '0' '0' ... '9' '9' '9']


In [6]:
# Converts RGB to a range between 0-1
xTrain = xTrain/255

In [7]:
xTrain = np.reshape(xTrain,(5010, 64, 64, 3))

In [8]:
input_shape = (64, 64, 3)

In [9]:
xTrain = xTrain.astype('float32')

In [10]:
# For encoding categorical variables and pre processing.
import sklearn.preprocessing as pre
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

encoder = pre.LabelBinarizer()
encoder.fit(yTrain)
outputs = encoder.transform(yTrain)

inputs = xTrain
inputs.shape
print(encoder)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)


In [11]:
# ------- MODEL -------
# Import keras.
import keras as kr
import tensorflow as tf

# Importing the required Keras modules containing model and layers
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D

# Start a neural network, building it by layers.
model = kr.models.Sequential()
# Add a hidden layer with 784 neurons.
model.add(Conv2D(64, kernel_size=(3,3), input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
model.add(Dense(256, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(50,activation=tf.nn.softmax))

# Add a 15 neuron output layer.
model.add(kr.layers.Dense(units=10, activation='softmax'))

C:\Users\niall\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 64)        1792      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 61504)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               15745280  
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                12850     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                510       
Total para

In [13]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# Number of Epoch is the amount of times the training set is put through the model
# The batch size is the amount of images the models processes at one time
model.fit(x=inputs,y=outputs, epochs=10, batch_size=100)

Epoch 1/10
5010/5010 [==============================] - 54s 11ms/step - loss: 2.3060 - acc: 0.0996
Epoch 2/10
5010/5010 [==============================] - 55s 11ms/step - loss: 2.3042 - acc: 0.1000
Epoch 3/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3035 - acc: 0.1000
Epoch 4/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3033 - acc: 0.0992
Epoch 5/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3030 - acc: 0.1020
Epoch 6/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3029 - acc: 0.1000
Epoch 7/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3028 - acc: 0.1000
Epoch 8/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3029 - acc: 0.1000
Epoch 9/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3028 - acc: 0.0920
Epoch 10/10
5010/5010 [==============================] - 52s 10ms/step - loss: 2.3028 - acc: 0.1000
